# Stress test to test upper bounds of concurrent pods
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argowf-chaos-
spec:
  entrypoint: argowf-chaos
  serviceAccountName: argo-chaos
  arguments:
    parameters:
      - name: appNamespace
        value: "default"
      - name: appLabel
        value: "nginx"
      - name: appEndpoint
        value: "nginx.yourdomain.com"
      - name: fileName
        value: "pod-app-kill-count.json"
  templates:
    - name: argowf-chaos
      steps:
        - - name: run-rbac
            template: run-rbac
        - - name: run-chaos
            template: run-chaos
        - - name: revert-rbac
            template: revert-rbac
        - - name: revert-chaos
            template: revert-chaos

    - name: run-rbac
      inputs:
        artifacts:
        - name: run-rbac
          path: /tmp/rbac.yaml
          raw:
            data: |
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: k8-pod-delete-sa
                namespace: {{workflow.parameters.appNamespace}}
                labels:
                  name: {{workflow.parameters.appLabel}}
              ---
              apiVersion: rbac.authorization.k8s.io/v1beta1
              kind: Role
              metadata:
                name: k8-pod-delete-sa
                namespace: {{workflow.parameters.appNamespace}}
                labels:
                  name: {{workflow.parameters.appLabel}}
              rules:
              - apiGroups: ["","litmuschaos.io","batch","apps"]
                resources: ["pods","deployments","jobs","configmaps","chaosengines","chaosexperiments","chaosresults"]
                verbs: ["create","list","get","patch","update","delete"]
              - apiGroups: [""]
                resources: ["nodes"]
                verbs : ["get","list"]
              ---
              apiVersion: rbac.authorization.k8s.io/v1beta1
              kind: RoleBinding
              metadata:
                name: k8-pod-delete-sa
                namespace: {{workflow.parameters.appNamespace}}
                labels:
                  name: {{workflow.parameters.appLabel}}
              roleRef:
                apiGroup: rbac.authorization.k8s.io
                kind: Role
                name: k8-pod-delete-sa
              subjects:
              - kind: ServiceAccount
                name: k8-pod-delete-sa
                namespace: {{workflow.parameters.appNamespace}}
      container:
        image: lachlanevenson/k8s-kubectl
        command: [sh, -c]
        args: ['kubectl apply -f /tmp/rbac.yaml -n {{workflow.parameters.appNamespace}} | sleep 20']

    - name: run-chaos
      inputs:
        artifacts:
        - name: run-chaos
          path: /tmp/delete.yaml
          raw:
            data: |
              # chaosengine.yaml
              apiVersion: litmuschaos.io/v1alpha1
              kind: ChaosEngine
              metadata:
                name: k8-pod-delete
                namespace: {{workflow.parameters.appNamespace}}
              spec:
                #ex. values: ns1:name=percona,ns2:run=nginx
                appinfo:
                  appns: {{workflow.parameters.appNamespace}}
                  # FYI, To see app label, apply kubectl get pods --show-labels
                  #applabel: "app=nginx"
                  applabel: "app={{workflow.parameters.appLabel}}"
                  appkind: deployment
                jobCleanUpPolicy: retain
                monitoring: false
                annotationCheck: 'false'
                engineState: 'active'
                chaosServiceAccount: k8-pod-delete-sa
                experiments:
                  - name: k8-pod-delete
                    spec:
                      components:
                        env:
                          - name: NAME_SPACE
                            value: {{workflow.parameters.appNamespace}}
                          - name: LABEL_NAME
                            value: {{workflow.parameters.appLabel}}
                          - name: APP_ENDPOINT
                            value: {{workflow.parameters.appEndpoint}}
                          - name: FILE
                            value: {{workflow.parameters.fileName}}
                          - name: REPORT
                            value: 'true'
                          - name: REPORT_ENDPOINT
                            value: 'https://eventbus-e2e.intuit.com/v2/ip-quality-reliability-realtime-prf'
      container:
        image: lachlanevenson/k8s-kubectl
        command: [sh, -c]
        args: ['kubectl create -f /tmp/delete.yaml -n {{workflow.parameters.appNamespace}} | sleep 60 ']

    - name: revert-rbac
      inputs:
        artifacts:
        - name: revert-rbac
          path: /tmp/rbac.yaml
          raw:
            data: |
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: k8-pod-delete-sa
                namespace: {{workflow.parameters.appNamespace}}
                labels:
                  name: {{workflow.parameters.appLabel}}
              ---
              apiVersion: rbac.authorization.k8s.io/v1beta1
              kind: Role
              metadata:
                name: k8-pod-delete-sa
                namespace: {{workflow.parameters.appNamespace}}
                labels:
                  name: {{workflow.parameters.appLabel}}
              rules:
              - apiGroups: ["","litmuschaos.io","batch","apps"]
                resources: ["pods","deployments","jobs","configmaps","chaosengines","chaosexperiments","chaosresults"]
                verbs: ["create","list","get","patch","update","delete"]
              - apiGroups: [""]
                resources: ["nodes"]
                verbs : ["get","list"]
              ---
              apiVersion: rbac.authorization.k8s.io/v1beta1
              kind: RoleBinding
              metadata:
                name: k8-pod-delete-sa
                namespace: {{workflow.parameters.appNamespace}}
                labels:
                  name: {{workflow.parameters.appLabel}}
              roleRef:
                apiGroup: rbac.authorization.k8s.io
                kind: Role
                name: k8-pod-delete-sa
              subjects:
              - kind: ServiceAccount
                name: k8-pod-delete-sa
                namespace: {{workflow.parameters.appNamespace}}
      container:
        image: lachlanevenson/k8s-kubectl
        command: [sh, -c]
        args: ['sleep 10 | kubectl delete -f /tmp/rbac.yaml -n {{workflow.parameters.appNamespace}} | sleep 20']

    - name: revert-chaos
      inputs:
        artifacts:
        - name: revert-chaos
          path: /tmp/delete.yaml
          raw:
            data: |
              # chaosengine.yaml
              apiVersion: litmuschaos.io/v1alpha1
              kind: ChaosEngine
              metadata:
                name: k8-pod-delete
                namespace: {{workflow.parameters.appNamespace}}
              spec:
                #ex. values: ns1:name=percona,ns2:run=nginx
                appinfo:
                  appns: {{workflow.parameters.appNamespace}}
                  # FYI, To see app label, apply kubectl get pods --show-labels
                  #applabel: "app=nginx"
                  applabel: "app={{workflow.parameters.appLabel}}"
                  appkind: deployment
                jobCleanUpPolicy: retain
                monitoring: false
                annotationCheck: 'false'
                engineState: 'active'
                chaosServiceAccount: k8-pod-delete-sa
                experiments:
                  - name: k8-pod-delete
                    spec:
                      components:
                        env:
                          - name: NAME_SPACE
                            value: {{workflow.parameters.appNamespace}}
                          - name: LABEL_NAME
                            value: {{workflow.parameters.appLabel}}
                          - name: APP_ENDPOINT
                            value: {{workflow.parameters.appEndpoint}}
                          - name: FILE
                            value: {{workflow.parameters.fileName}}
                          - name: REPORT
                            value: 'true'
                          - name: REPORT_ENDPOINT
                            value: 'https://eventbus-e2e.intuit.com/v2/ip-quality-reliability-realtime-prf'
      container:
        image: lachlanevenson/k8s-kubectl
        command: [sh, -c]
        args: [' sleep 20 | kubectl delete  -f /tmp/delete.yaml -n {{workflow.parameters.appNamespace}}']
