# Stress test to test upper bounds of concurrent pods
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argowf-chaos-
spec:
  entrypoint: argowf-chaos
  serviceAccountName: argo-chaos
  arguments:
    parameters:
      - name: appNamespace
        value: "kube-system"
      - name: appCurrentNamespace
        value: "default"
      - name: appLabel
        value: "nginx"
      - name: appEndpoint
        value: "nginx.yourdomain.com"
      - name: fileName
        value: "pod-app-kill-count.json"
  templates:
    - name: argowf-chaos
      steps:
        - - name: run-chaos
            template: run-chaos
        - - name: revert-chaos
            template: revert-chaos

    - name: run-chaos
      inputs:
        artifacts:
        - name: run-chaos
          path: /tmp/delete.yaml
          raw:
            data: |
              # chaosengine.yaml
              apiVersion: litmuschaos.io/v1alpha1
              kind: ChaosEngine
              metadata:
                name: k8-pod-delete
                namespace: {{workflow.parameters.appCurrentNamespace}}
              spec:
                #ex. values: ns1:name=percona,ns2:run=nginx
                appinfo:
                  appns: {{workflow.parameters.appNamespace}}
                  # FYI, To see app label, apply kubectl get pods --show-labels
                  #applabel: "app=nginx"
                  applabel: "app={{workflow.parameters.appLabel}}"
                  appkind: deployment
                jobCleanUpPolicy: retain
                monitoring: false
                annotationCheck: 'false'
                engineState: 'active'
                # this account has been created as part of rbac - rbac-admin.yaml
                chaosServiceAccount: chaos-admin
                experiments:
                  - name: k8-pod-delete
                    spec:
                      components:
                        env:
                          - name: NAME_SPACE
                            value: {{workflow.parameters.appNamespace}}
                          - name: LABEL_NAME
                            value: {{workflow.parameters.appLabel}}
                          - name: APP_ENDPOINT
                            value: {{workflow.parameters.appEndpoint}}
                          - name: FILE
                            value: {{workflow.parameters.fileName}}
                          - name: REPORT
                            value: 'true'
                          - name: REPORT_ENDPOINT
                            value: 'none'
      container:
        image: lachlanevenson/k8s-kubectl
        command: [sh, -c]
        args: ['kubectl apply -f /tmp/delete.yaml -n {{workflow.parameters.appCurrentNamespace}} | echo "sleeping for 60s" | sleep 60 ']

    - name: revert-chaos
      inputs:
        artifacts:
        - name: revert-chaos
          path: /tmp/delete.yaml
          raw:
            data: |
              # chaosengine.yaml
              apiVersion: litmuschaos.io/v1alpha1
              kind: ChaosEngine
              metadata:
                name: k8-pod-delete
                namespace: {{workflow.parameters.appCurrentNamespace}}
              spec:
                #ex. values: ns1:name=percona,ns2:run=nginx
                appinfo:
                  appns: {{workflow.parameters.appNamespace}}
                  # FYI, To see app label, apply kubectl get pods --show-labels
                  #applabel: "app=nginx"
                  applabel: "app={{workflow.parameters.appLabel}}"
                  appkind: deployment
                jobCleanUpPolicy: retain
                monitoring: false
                annotationCheck: 'false'
                engineState: 'active'
                chaosServiceAccount: chaos-admin
                experiments:
                  - name: k8-pod-delete
                    spec:
                      components:
                        env:
                          - name: NAME_SPACE
                            value: {{workflow.parameters.appNamespace}}
                          - name: LABEL_NAME
                            value: {{workflow.parameters.appLabel}}
                          - name: APP_ENDPOINT
                            value: {{workflow.parameters.appEndpoint}}
                          - name: FILE
                            value:  {{workflow.parameters.fileName}}
                          - name: REPORT
                            value: 'true'
                          - name: REPORT_ENDPOINT
                            value: 'none'
      container:
        image: lachlanevenson/k8s-kubectl
        command: [sh, -c]
        args: [' sleep 20 | kubectl delete  -f /tmp/delete.yaml -n {{workflow.parameters.appCurrentNamespace}}']
